apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: arifjmamun/ticketing-auth-dotnet
          env:
            - name: ASPNETCORE_ConnectionStrings__AuthDbContext
              value: "Username=postgres;Password=postgres;Host=auth-postgres-srv;Port=5432;Database=AuthDb"
            - name: ASPNETCORE_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 80